version: '3.8'

services:
  secret_manager:
    image: maissacrement/secret-manager:0.0.3
    #build: .
    environment:
      - USER=test
    user: root
    volumes:
      - ./cmd/update:/etc/incron/cmd/update
      - ./app.py:/usr/bin/secret-manager
      - /var/run/docker.sock:/var/run/docker.sock