#!/bin/sh
set -e
for f in `ls -laR $1 | grep ":$" | cut -d':' -f1`
do
    files=`find $f -maxdepth 1 -mindepth 1 -type f`
    for file in $files
    do
        exec 3<$file ; rm $file; envsubst <&3 >$file ;  exec 3>&-
        echo "$file:" >> /var/log/test; cat $file >> /var/log/test; echo >> /var/log/test
    done
done
